# permissions for end users to edit mysqlclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: mysqlcluster-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: mysql-operator
    app.kubernetes.io/part-of: mysql-operator
    app.kubernetes.io/managed-by: kustomize
  name: mysqlcluster-editor-role
rules:
- apiGroups:
  - db.imind.tech
  resources:
  - mysqlclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - db.imind.tech
  resources:
  - mysqlclusters/status
  verbs:
  - get
