apiVersion: v1
kind: Service
metadata:
  name: {{.ObjectMeta.Name}}
  namespace: {{.ObjectMeta.Namespace}}
spec:
  ports:
    - port: 3306
      name: client
    - port: 3307
      name: back
  clusterIP: None
  selector:
    app: {{.ObjectMeta.Name}}